// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slhtenivgwgjvwjsshap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsaHRlbml2Z3dnanZ3anNzaGFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MjQ1MzQsImV4cCI6MjA1ODMwMDUzNH0.76TtdqdGPknf5r_0PhIkxLTfoe_KEDhIez5f7RoJC5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);